name: build-and-push-to-acr

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-push:
    environment: PROD
    name: Build and Push Image
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.set-meta.outputs.image }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine image tag
        id: set-meta
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            TAG=${{ github.event.release.tag_name }}
          else
            TAG=latest
          fi

          IMAGE="${{ secrets.ACR_LOGIN_SERVER }}/${{ vars.IMAGE_APP_NAME }}:$TAG"

          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

          echo "Using tag: $TAG"

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}
            ${{ secrets.ACR_LOGIN_SERVER }}/${{ vars.IMAGE_APP_NAME }}:latest
