name: sync-vm

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build-and-push-to-acr"]
    types: [completed]

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_ZENTRA }}" > ~/.ssh/vm_key.pem
          chmod 400 ~/.ssh/vm_key.pem
          ssh-keyscan -H "${{ secrets.AZURE_VM_IP }}" >> ~/.ssh/known_hosts
      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Copy docker-compose file
        run: |
          scp -i ~/.ssh/vm_key.pem docker-compose.prod.yml azureuser@"${{ secrets.AZURE_VM_IP }}":~/zentra/docker-compose.prod.yml

      - name: Sync env
        env:
          AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
          NODE_ENV: ${{ vars.NODE_ENV }}
          EXPRESS_PORT: ${{ vars.EXPRESS_PORT }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          DISCORD_STANDUP_CHANNEL_ID: ${{ secrets.DISCORD_STANDUP_CHANNEL_ID }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_PROVIDER_NAME: ${{ vars.LLM_PROVIDER_NAME }}
          LLM_MODEL_NAME: ${{ vars.LLM_MODEL_NAME }}
          API_BASE_URL: ${{ vars.API_BASE_URL }}
          TRADING_SUMMARY_URL: ${{ vars.TRADING_SUMMARY_URL }}
          LOG_HOT_ROTATE: ${{ vars.LOG_HOT_ROTATE }}
          LOG_COLD_ROTATE: ${{ vars.LOG_COLD_ROTATE }}
        run: |
          ssh -i ~/.ssh/vm_key.pem azureuser@"$AZURE_VM_IP" << "EOF"
            set -e

            cd ~/zentra

            echo 'Writing .env'

            rm -f .env

            echo NODE_ENV=$NODE_ENV >> .env
            echo EXPRESS_PORT=$EXPRESS_PORT >> .env
            echo DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN >> .env
            echo DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID >> .env
            echo DISCORD_GUILD_ID=$DISCORD_GUILD_ID >> .env
            echo DISCORD_STANDUP_CHANNEL_ID=$DISCORD_STANDUP_CHANNEL_ID >> .env
            echo LLM_API_KEY=$LLM_API_KEY >> .env
            echo LLM_PROVIDER_NAME=$LLM_PROVIDER_NAME >> .env
            echo LLM_MODEL_NAME=$LLM_MODEL_NAME >> .env
            echo API_BASE_URL=$API_BASE_URL >> .env
            echo TRADING_SUMMARY_URL=$TRADING_SUMMARY_URL >> .env
            echo LOG_HOT_ROTATE=$LOG_HOT_ROTATE >> .env
            echo LOG_COLD_ROTATE=$LOG_COLD_ROTATE >> .env

            echo 'Sync complete'
          EOF