name: deploy-to-vm

on:
  workflow_run:
    workflows: ["build-and-push-to-acr"]
    types: [completed]

  workflow_dispatch:

jobs:
  deploy:
    environment: PROD
    name: Deploy to VM
    runs-on: ubuntu-latest

    if: >
      ${{
        github.event_name == 'workflow_dispatch' ||
        github.event.workflow_run.conclusion == 'success'
      }}

    steps:   
      - name: Setup SSH trust
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_ZENTRA }}" > vm_key.pem
          chmod 400 vm_key.pem

          ssh-keyscan -H "${{ secrets.AZURE_VM_IP }}" >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i vm_key.pem azureuser@${{ secrets.AZURE_VM_IP }} << EOF
            echo "Connected to VM. Deploying application..."
            set -e

            echo "Logging in to ACR"

            echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} \
              -u "${{ secrets.ACR_USERNAME }}" \
              --password-stdin

            echo "Pulling image"
            
            docker pull ${{ secrets.ACR_LOGIN_SERVER }}/${{ vars.IMAGE_APP_NAME }}:latest

            echo "Stopping existing container (if any)"

            docker stop zentra || true
            docker rm zentra || true

            echo "Running new container with environment variables..."

            docker run -d \
              --restart unless-stopped \
              --name zentra \
              -p ${{ vars.EXPRESS_PORT }}:${{ vars.EXPRESS_PORT }} \
              -e NODE_ENV=${{ vars.NODE_ENV }} \
              -e EXPRESS_PORT=${{ vars.EXPRESS_PORT }} \
              -e DISCORD_BOT_TOKEN="${{ secrets.DISCORD_BOT_TOKEN }}" \
              -e DISCORD_CLIENT_ID="${{ secrets.DISCORD_CLIENT_ID }}" \
              -e DISCORD_GUILD_ID="${{ secrets.DISCORD_GUILD_ID }}" \
              -e DISCORD_STANDUP_CHANNEL_ID="${{ secrets.DISCORD_STANDUP_CHANNEL_ID }}" \
              -e LLM_API_KEY="${{ secrets.LLM_API_KEY }}" \
              -e LLM_PROVIDER_NAME="${{ vars.LLM_PROVIDER_NAME }}" \
              -e LLM_MODEL_NAME="${{ vars.LLM_MODEL_NAME }}" \
              -e GITHUB_PERSONAL_ACCESS_TOKEN="${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" \
              -e GITHUB_OWNER_USERNAME="${{ vars.GH_OWNER_USERNAME }}" \
              -e GITHUB_REPOSITORY_NAME="${{ vars.GH_REPOSITORY_NAME }}" \
              -e WEBHOOK_BASE_URL="${{ secrets.WEBHOOK_BASE_URL }}" \
              -e API_BASE_URL="${{ secrets.API_BASE_URL }}" \
              ${{ secrets.ACR_LOGIN_SERVER }}/${{ vars.IMAGE_APP_NAME }}:latest
          EOF