name: deploy-to-vm

on:
  workflow_run:
    workflows: ["build-and-push-to-acr"]
    types: [completed]

  workflow_dispatch:

jobs:
  deploy:
    environment: PROD
    name: Deploy to VM
    runs-on: ubuntu-latest

    if: >
      ${{
        github.event_name == 'workflow_dispatch' ||
        github.event.workflow_run.conclusion == 'success'
      }}

    steps:   
      - name: Setup SSH trust
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_ZENTRA }}" > ~/.ssh/vm_key.pem
          chmod 400 ~/.ssh/vm_key.pem
          ssh-keyscan -H "${{ secrets.AZURE_VM_IP }}" >> ~/.ssh/known_hosts

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/vm_key.pem azureuser@${{ secrets.AZURE_VM_IP }} << EOF
            echo "Connected to VM. Deploying application..."
            set -e
            
            cd ./zentra

            echo "Creating .env..."

            cat > .env <<EOT
            ACR_LOGIN_SERVER=${{ secrets.ACR_LOGIN_SERVER }}
            IMAGE_APP_NAME=${{ vars.IMAGE_APP_NAME }}

            NODE_ENV=${{ vars.NODE_ENV }}
            EXPRESS_PORT=${{ vars.EXPRESS_PORT }}

            DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
            DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}
            DISCORD_GUILD_ID=${{ secrets.DISCORD_GUILD_ID }}
            DISCORD_STANDUP_CHANNEL_ID=${{ secrets.DISCORD_STANDUP_CHANNEL_ID }}

            LLM_API_KEY=${{ secrets.LLM_API_KEY }}
            LLM_PROVIDER_NAME=${{ vars.LLM_PROVIDER_NAME }}
            LLM_MODEL_NAME=${{ vars.LLM_MODEL_NAME }}

            API_BASE_URL=${{ vars.API_BASE_URL }}
            TRADING_SUMMARY_URL=${{ vars.MARKET_SUMMARY_URL }}
            
            LOG_HOT_ROTATE=${{ vars.LOG_HOT_ROTATE }}
            LOG_COLD_ROTATE=${{ vars.LOG_COLD_ROTATE }}
            EOT

            echo "Logging in to ACR"

            echo "${{ secrets.ACR_PASSWORD }}" | docker login \
              ${{ secrets.ACR_LOGIN_SERVER }} \
              -u "${{ secrets.ACR_USERNAME }}" \
              --password-stdin

            echo "Pulling latest image"
            docker compose -f docker-compose.prod.yml pull

            echo "Deploying"
            docker compose -f docker-compose.prod.yml up -d

            echo "Cleaning"
            docker image prune -f

            echo "Remove .env file"
            rm -f .env
            
            echo "Deployment completed successfully"
          EOF
